# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20161129_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publicate_at',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 30, 14, 35, 54, 280251)),
        ),
    ]
